/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from '@prisma/client/runtime/index-browser';

export type * from '../models';
export type * from './prismaNamespace';

export const Decimal = runtime.Decimal;

export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as new (secret: never) => typeof runtime.DbNull,
  JsonNull: runtime.NullTypes.JsonNull as new (secret: never) => typeof runtime.JsonNull,
  AnyNull: runtime.NullTypes.AnyNull as new (secret: never) => typeof runtime.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull;

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull;

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull;

export const ModelName = {
  Zipline: 'Zipline',
  User: 'User',
  Export: 'Export',
  UserSession: 'UserSession',
  UserQuota: 'UserQuota',
  UserPasskey: 'UserPasskey',
  OAuthProvider: 'OAuthProvider',
  File: 'File',
  FileShare: 'FileShare',
  Thumbnail: 'Thumbnail',
  Folder: 'Folder',
  IncompleteFile: 'IncompleteFile',
  Tag: 'Tag',
  Url: 'Url',
  Metric: 'Metric',
  Invite: 'Invite',
} as const;

export type ModelName = (typeof ModelName)[keyof typeof ModelName];

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable',
} as const);

export type TransactionIsolationLevel =
  (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel];

export const ZiplineScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  firstSetup: 'firstSetup',
  coreReturnHttpsUrls: 'coreReturnHttpsUrls',
  coreDefaultDomain: 'coreDefaultDomain',
  coreTempDirectory: 'coreTempDirectory',
  coreTrustProxy: 'coreTrustProxy',
  chunksEnabled: 'chunksEnabled',
  chunksMax: 'chunksMax',
  chunksSize: 'chunksSize',
  tasksDeleteInterval: 'tasksDeleteInterval',
  tasksClearInvitesInterval: 'tasksClearInvitesInterval',
  tasksMaxViewsInterval: 'tasksMaxViewsInterval',
  tasksThumbnailsInterval: 'tasksThumbnailsInterval',
  tasksMetricsInterval: 'tasksMetricsInterval',
  tasksCleanThumbnailsInterval: 'tasksCleanThumbnailsInterval',
  filesRoute: 'filesRoute',
  filesLength: 'filesLength',
  filesDefaultFormat: 'filesDefaultFormat',
  filesDisabledTypes: 'filesDisabledTypes',
  filesDisabledTypesDefault: 'filesDisabledTypesDefault',
  filesDisabledExtensions: 'filesDisabledExtensions',
  filesMaxFileSize: 'filesMaxFileSize',
  filesDefaultExpiration: 'filesDefaultExpiration',
  filesMaxExpiration: 'filesMaxExpiration',
  filesAssumeMimetypes: 'filesAssumeMimetypes',
  filesDefaultDateFormat: 'filesDefaultDateFormat',
  filesRemoveGpsMetadata: 'filesRemoveGpsMetadata',
  filesRandomWordsNumAdjectives: 'filesRandomWordsNumAdjectives',
  filesRandomWordsSeparator: 'filesRandomWordsSeparator',
  filesDefaultCompressionFormat: 'filesDefaultCompressionFormat',
  filesMaxFilesPerUpload: 'filesMaxFilesPerUpload',
  filesExtensionlessUrls: 'filesExtensionlessUrls',
  urlsRoute: 'urlsRoute',
  urlsLength: 'urlsLength',
  featuresImageCompression: 'featuresImageCompression',
  featuresRobotsTxt: 'featuresRobotsTxt',
  featuresHealthcheck: 'featuresHealthcheck',
  featuresUserRegistration: 'featuresUserRegistration',
  featuresOauthRegistration: 'featuresOauthRegistration',
  featuresDeleteOnMaxViews: 'featuresDeleteOnMaxViews',
  featuresFilesPrivateByDefault: 'featuresFilesPrivateByDefault',
  featuresThumbnailsEnabled: 'featuresThumbnailsEnabled',
  featuresThumbnailsNumberThreads: 'featuresThumbnailsNumberThreads',
  featuresThumbnailsFormat: 'featuresThumbnailsFormat',
  featuresThumbnailsInstantaneous: 'featuresThumbnailsInstantaneous',
  featuresMetricsEnabled: 'featuresMetricsEnabled',
  featuresMetricsAdminOnly: 'featuresMetricsAdminOnly',
  featuresMetricsShowUserSpecific: 'featuresMetricsShowUserSpecific',
  featuresVersionChecking: 'featuresVersionChecking',
  invitesEnabled: 'invitesEnabled',
  invitesLength: 'invitesLength',
  websiteTitle: 'websiteTitle',
  websiteTitleLogo: 'websiteTitleLogo',
  websiteExternalLinks: 'websiteExternalLinks',
  websiteLoginBackground: 'websiteLoginBackground',
  websiteLoginBackgroundBlur: 'websiteLoginBackgroundBlur',
  websiteDefaultAvatar: 'websiteDefaultAvatar',
  websiteTos: 'websiteTos',
  websiteThemeDefault: 'websiteThemeDefault',
  websiteThemeDark: 'websiteThemeDark',
  websiteThemeLight: 'websiteThemeLight',
  oauthBypassLocalLogin: 'oauthBypassLocalLogin',
  oauthLoginOnly: 'oauthLoginOnly',
  oauthDiscordClientId: 'oauthDiscordClientId',
  oauthDiscordClientSecret: 'oauthDiscordClientSecret',
  oauthDiscordRedirectUri: 'oauthDiscordRedirectUri',
  oauthDiscordAllowedIds: 'oauthDiscordAllowedIds',
  oauthDiscordDeniedIds: 'oauthDiscordDeniedIds',
  oauthGoogleClientId: 'oauthGoogleClientId',
  oauthGoogleClientSecret: 'oauthGoogleClientSecret',
  oauthGoogleRedirectUri: 'oauthGoogleRedirectUri',
  oauthGithubClientId: 'oauthGithubClientId',
  oauthGithubClientSecret: 'oauthGithubClientSecret',
  oauthGithubRedirectUri: 'oauthGithubRedirectUri',
  oauthOidcClientId: 'oauthOidcClientId',
  oauthOidcClientSecret: 'oauthOidcClientSecret',
  oauthOidcAuthorizeUrl: 'oauthOidcAuthorizeUrl',
  oauthOidcTokenUrl: 'oauthOidcTokenUrl',
  oauthOidcUserinfoUrl: 'oauthOidcUserinfoUrl',
  oauthOidcRedirectUri: 'oauthOidcRedirectUri',
  mfaTotpEnabled: 'mfaTotpEnabled',
  mfaTotpIssuer: 'mfaTotpIssuer',
  mfaPasskeysEnabled: 'mfaPasskeysEnabled',
  mfaPasskeysRpID: 'mfaPasskeysRpID',
  mfaPasskeysOrigin: 'mfaPasskeysOrigin',
  ratelimitEnabled: 'ratelimitEnabled',
  ratelimitMax: 'ratelimitMax',
  ratelimitWindow: 'ratelimitWindow',
  ratelimitAdminBypass: 'ratelimitAdminBypass',
  ratelimitAllowList: 'ratelimitAllowList',
  httpWebhookOnUpload: 'httpWebhookOnUpload',
  httpWebhookOnShorten: 'httpWebhookOnShorten',
  discordWebhookUrl: 'discordWebhookUrl',
  discordUsername: 'discordUsername',
  discordAvatarUrl: 'discordAvatarUrl',
  discordOnUploadWebhookUrl: 'discordOnUploadWebhookUrl',
  discordOnUploadUsername: 'discordOnUploadUsername',
  discordOnUploadAvatarUrl: 'discordOnUploadAvatarUrl',
  discordOnUploadContent: 'discordOnUploadContent',
  discordOnUploadEmbed: 'discordOnUploadEmbed',
  discordOnShortenWebhookUrl: 'discordOnShortenWebhookUrl',
  discordOnShortenUsername: 'discordOnShortenUsername',
  discordOnShortenAvatarUrl: 'discordOnShortenAvatarUrl',
  discordOnShortenContent: 'discordOnShortenContent',
  discordOnShortenEmbed: 'discordOnShortenEmbed',
  pwaEnabled: 'pwaEnabled',
  pwaTitle: 'pwaTitle',
  pwaShortName: 'pwaShortName',
  pwaDescription: 'pwaDescription',
  pwaThemeColor: 'pwaThemeColor',
  pwaBackgroundColor: 'pwaBackgroundColor',
  domains: 'domains',
} as const;

export type ZiplineScalarFieldEnum = (typeof ZiplineScalarFieldEnum)[keyof typeof ZiplineScalarFieldEnum];

export const UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  username: 'username',
  password: 'password',
  avatar: 'avatar',
  token: 'token',
  role: 'role',
  view: 'view',
  totpSecret: 'totpSecret',
} as const;

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum];

export const ExportScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  completed: 'completed',
  path: 'path',
  files: 'files',
  size: 'size',
  userId: 'userId',
} as const;

export type ExportScalarFieldEnum = (typeof ExportScalarFieldEnum)[keyof typeof ExportScalarFieldEnum];

export const UserSessionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  ua: 'ua',
  client: 'client',
  device: 'device',
  userId: 'userId',
} as const;

export type UserSessionScalarFieldEnum =
  (typeof UserSessionScalarFieldEnum)[keyof typeof UserSessionScalarFieldEnum];

export const UserQuotaScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  filesQuota: 'filesQuota',
  maxBytes: 'maxBytes',
  maxFiles: 'maxFiles',
  maxUrls: 'maxUrls',
  userId: 'userId',
} as const;

export type UserQuotaScalarFieldEnum =
  (typeof UserQuotaScalarFieldEnum)[keyof typeof UserQuotaScalarFieldEnum];

export const UserPasskeyScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastUsed: 'lastUsed',
  name: 'name',
  reg: 'reg',
  userId: 'userId',
} as const;

export type UserPasskeyScalarFieldEnum =
  (typeof UserPasskeyScalarFieldEnum)[keyof typeof UserPasskeyScalarFieldEnum];

export const OAuthProviderScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  provider: 'provider',
  username: 'username',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  oauthId: 'oauthId',
} as const;

export type OAuthProviderScalarFieldEnum =
  (typeof OAuthProviderScalarFieldEnum)[keyof typeof OAuthProviderScalarFieldEnum];

export const FileScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletesAt: 'deletesAt',
  name: 'name',
  originalName: 'originalName',
  size: 'size',
  type: 'type',
  views: 'views',
  maxViews: 'maxViews',
  favorite: 'favorite',
  password: 'password',
  anonymous: 'anonymous',
  userId: 'userId',
  folderId: 'folderId',
} as const;

export type FileScalarFieldEnum = (typeof FileScalarFieldEnum)[keyof typeof FileScalarFieldEnum];

export const FileShareScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  token: 'token',
  fileId: 'fileId',
  expiresAt: 'expiresAt',
  maxViews: 'maxViews',
  views: 'views',
  password: 'password',
} as const;

export type FileShareScalarFieldEnum =
  (typeof FileShareScalarFieldEnum)[keyof typeof FileShareScalarFieldEnum];

export const ThumbnailScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  path: 'path',
  fileId: 'fileId',
} as const;

export type ThumbnailScalarFieldEnum =
  (typeof ThumbnailScalarFieldEnum)[keyof typeof ThumbnailScalarFieldEnum];

export const FolderScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  public: 'public',
  allowUploads: 'allowUploads',
  parentId: 'parentId',
  userId: 'userId',
} as const;

export type FolderScalarFieldEnum = (typeof FolderScalarFieldEnum)[keyof typeof FolderScalarFieldEnum];

export const IncompleteFileScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status',
  chunksTotal: 'chunksTotal',
  chunksComplete: 'chunksComplete',
  metadata: 'metadata',
  userId: 'userId',
} as const;

export type IncompleteFileScalarFieldEnum =
  (typeof IncompleteFileScalarFieldEnum)[keyof typeof IncompleteFileScalarFieldEnum];

export const TagScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  color: 'color',
  userId: 'userId',
} as const;

export type TagScalarFieldEnum = (typeof TagScalarFieldEnum)[keyof typeof TagScalarFieldEnum];

export const UrlScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  code: 'code',
  vanity: 'vanity',
  destination: 'destination',
  views: 'views',
  maxViews: 'maxViews',
  password: 'password',
  enabled: 'enabled',
  userId: 'userId',
} as const;

export type UrlScalarFieldEnum = (typeof UrlScalarFieldEnum)[keyof typeof UrlScalarFieldEnum];

export const MetricScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  data: 'data',
} as const;

export type MetricScalarFieldEnum = (typeof MetricScalarFieldEnum)[keyof typeof MetricScalarFieldEnum];

export const InviteScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt',
  code: 'code',
  uses: 'uses',
  maxUses: 'maxUses',
  inviterId: 'inviterId',
} as const;

export type InviteScalarFieldEnum = (typeof InviteScalarFieldEnum)[keyof typeof InviteScalarFieldEnum];

export const SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

export const JsonNullValueInput = {
  JsonNull: JsonNull,
} as const;

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput];

export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull,
} as const;

export type NullableJsonNullValueInput =
  (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput];

export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive',
} as const;

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode];

export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull,
} as const;

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter];

export const NullsOrder = {
  first: 'first',
  last: 'last',
} as const;

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder];
