/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser.
 * Use it to get access to models, enums, and input types.
 *
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser';
export { Prisma };
export * as $Enums from './enums';
export * from './enums';
/**
 * Model Zipline
 *
 */
export type Zipline = Prisma.ZiplineModel;
/**
 * Model User
 *
 */
export type User = Prisma.UserModel;
/**
 * Model Export
 *
 */
export type Export = Prisma.ExportModel;
/**
 * Model UserSession
 *
 */
export type UserSession = Prisma.UserSessionModel;
/**
 * Model UserQuota
 *
 */
export type UserQuota = Prisma.UserQuotaModel;
/**
 * Model UserPasskey
 *
 */
export type UserPasskey = Prisma.UserPasskeyModel;
/**
 * Model OAuthProvider
 *
 */
export type OAuthProvider = Prisma.OAuthProviderModel;
/**
 * Model File
 *
 */
export type File = Prisma.FileModel;
/**
 * Model FileShare
 *
 */
export type FileShare = Prisma.FileShareModel;
/**
 * Model Thumbnail
 *
 */
export type Thumbnail = Prisma.ThumbnailModel;
/**
 * Model Folder
 *
 */
export type Folder = Prisma.FolderModel;
/**
 * Model IncompleteFile
 *
 */
export type IncompleteFile = Prisma.IncompleteFileModel;
/**
 * Model Tag
 *
 */
export type Tag = Prisma.TagModel;
/**
 * Model Url
 *
 */
export type Url = Prisma.UrlModel;
/**
 * Model Metric
 *
 */
export type Metric = Prisma.MetricModel;
/**
 * Model Invite
 *
 */
export type Invite = Prisma.InviteModel;
