/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url));

import * as runtime from '@prisma/client/runtime/client';
import * as $Enums from './enums';
import * as $Class from './internal/class';
import * as Prisma from './internal/prismaNamespace';

export * as $Enums from './enums';
export * from './enums';
/**
 * ## Prisma Client
 *
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Ziplines
 * const ziplines = await prisma.zipline.findMany()
 * ```
 *
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass();
export type PrismaClient<
  LogOpts extends Prisma.LogLevel = never,
  OmitOpts extends Prisma.PrismaClientOptions['omit'] = Prisma.PrismaClientOptions['omit'],
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>;
export { Prisma };

/**
 * Model Zipline
 *
 */
export type Zipline = Prisma.ZiplineModel;
/**
 * Model User
 *
 */
export type User = Prisma.UserModel;
/**
 * Model Export
 *
 */
export type Export = Prisma.ExportModel;
/**
 * Model UserSession
 *
 */
export type UserSession = Prisma.UserSessionModel;
/**
 * Model UserQuota
 *
 */
export type UserQuota = Prisma.UserQuotaModel;
/**
 * Model UserPasskey
 *
 */
export type UserPasskey = Prisma.UserPasskeyModel;
/**
 * Model OAuthProvider
 *
 */
export type OAuthProvider = Prisma.OAuthProviderModel;
/**
 * Model File
 *
 */
export type File = Prisma.FileModel;
/**
 * Model FileShare
 *
 */
export type FileShare = Prisma.FileShareModel;
/**
 * Model Thumbnail
 *
 */
export type Thumbnail = Prisma.ThumbnailModel;
/**
 * Model Folder
 *
 */
export type Folder = Prisma.FolderModel;
/**
 * Model IncompleteFile
 *
 */
export type IncompleteFile = Prisma.IncompleteFileModel;
/**
 * Model Tag
 *
 */
export type Tag = Prisma.TagModel;
/**
 * Model Url
 *
 */
export type Url = Prisma.UrlModel;
/**
 * Model Metric
 *
 */
export type Metric = Prisma.MetricModel;
/**
 * Model Invite
 *
 */
export type Invite = Prisma.InviteModel;
