/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `FileShare` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model FileShare
 *
 */
export type FileShareModel = runtime.Types.Result.DefaultSelection<Prisma.$FileSharePayload>;

export type AggregateFileShare = {
  _count: FileShareCountAggregateOutputType | null;
  _avg: FileShareAvgAggregateOutputType | null;
  _sum: FileShareSumAggregateOutputType | null;
  _min: FileShareMinAggregateOutputType | null;
  _max: FileShareMaxAggregateOutputType | null;
};

export type FileShareAvgAggregateOutputType = {
  maxViews: number | null;
  views: number | null;
};

export type FileShareSumAggregateOutputType = {
  maxViews: number | null;
  views: number | null;
};

export type FileShareMinAggregateOutputType = {
  id: string | null;
  createdAt: Date | null;
  updatedAt: Date | null;
  token: string | null;
  fileId: string | null;
  expiresAt: Date | null;
  maxViews: number | null;
  views: number | null;
  password: string | null;
};

export type FileShareMaxAggregateOutputType = {
  id: string | null;
  createdAt: Date | null;
  updatedAt: Date | null;
  token: string | null;
  fileId: string | null;
  expiresAt: Date | null;
  maxViews: number | null;
  views: number | null;
  password: string | null;
};

export type FileShareCountAggregateOutputType = {
  id: number;
  createdAt: number;
  updatedAt: number;
  token: number;
  fileId: number;
  expiresAt: number;
  maxViews: number;
  views: number;
  password: number;
  _all: number;
};

export type FileShareAvgAggregateInputType = {
  maxViews?: true;
  views?: true;
};

export type FileShareSumAggregateInputType = {
  maxViews?: true;
  views?: true;
};

export type FileShareMinAggregateInputType = {
  id?: true;
  createdAt?: true;
  updatedAt?: true;
  token?: true;
  fileId?: true;
  expiresAt?: true;
  maxViews?: true;
  views?: true;
  password?: true;
};

export type FileShareMaxAggregateInputType = {
  id?: true;
  createdAt?: true;
  updatedAt?: true;
  token?: true;
  fileId?: true;
  expiresAt?: true;
  maxViews?: true;
  views?: true;
  password?: true;
};

export type FileShareCountAggregateInputType = {
  id?: true;
  createdAt?: true;
  updatedAt?: true;
  token?: true;
  fileId?: true;
  expiresAt?: true;
  maxViews?: true;
  views?: true;
  password?: true;
  _all?: true;
};

export type FileShareAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which FileShare to aggregate.
   */
  where?: Prisma.FileShareWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of FileShares to fetch.
   */
  orderBy?: Prisma.FileShareOrderByWithRelationInput | Prisma.FileShareOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.FileShareWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` FileShares from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` FileShares.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned FileShares
   **/
  _count?: true | FileShareCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: FileShareAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: FileShareSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: FileShareMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: FileShareMaxAggregateInputType;
};

export type GetFileShareAggregateType<T extends FileShareAggregateArgs> = {
  [P in keyof T & keyof AggregateFileShare]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFileShare[P]>
    : Prisma.GetScalarType<T[P], AggregateFileShare[P]>;
};

export type FileShareGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.FileShareWhereInput;
  orderBy?: Prisma.FileShareOrderByWithAggregationInput | Prisma.FileShareOrderByWithAggregationInput[];
  by: Prisma.FileShareScalarFieldEnum[] | Prisma.FileShareScalarFieldEnum;
  having?: Prisma.FileShareScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: FileShareCountAggregateInputType | true;
  _avg?: FileShareAvgAggregateInputType;
  _sum?: FileShareSumAggregateInputType;
  _min?: FileShareMinAggregateInputType;
  _max?: FileShareMaxAggregateInputType;
};

export type FileShareGroupByOutputType = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  token: string;
  fileId: string;
  expiresAt: Date | null;
  maxViews: number | null;
  views: number;
  password: string | null;
  _count: FileShareCountAggregateOutputType | null;
  _avg: FileShareAvgAggregateOutputType | null;
  _sum: FileShareSumAggregateOutputType | null;
  _min: FileShareMinAggregateOutputType | null;
  _max: FileShareMaxAggregateOutputType | null;
};

export type GetFileShareGroupByPayload<T extends FileShareGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FileShareGroupByOutputType, T['by']> & {
      [P in keyof T & keyof FileShareGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], FileShareGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], FileShareGroupByOutputType[P]>;
    }
  >
>;

export type FileShareWhereInput = {
  AND?: Prisma.FileShareWhereInput | Prisma.FileShareWhereInput[];
  OR?: Prisma.FileShareWhereInput[];
  NOT?: Prisma.FileShareWhereInput | Prisma.FileShareWhereInput[];
  id?: Prisma.StringFilter<'FileShare'> | string;
  createdAt?: Prisma.DateTimeFilter<'FileShare'> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<'FileShare'> | Date | string;
  token?: Prisma.StringFilter<'FileShare'> | string;
  fileId?: Prisma.StringFilter<'FileShare'> | string;
  expiresAt?: Prisma.DateTimeNullableFilter<'FileShare'> | Date | string | null;
  maxViews?: Prisma.IntNullableFilter<'FileShare'> | number | null;
  views?: Prisma.IntFilter<'FileShare'> | number;
  password?: Prisma.StringNullableFilter<'FileShare'> | string | null;
  file?: Prisma.XOR<Prisma.FileScalarRelationFilter, Prisma.FileWhereInput>;
};

export type FileShareOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  token?: Prisma.SortOrder;
  fileId?: Prisma.SortOrder;
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder;
  maxViews?: Prisma.SortOrderInput | Prisma.SortOrder;
  views?: Prisma.SortOrder;
  password?: Prisma.SortOrderInput | Prisma.SortOrder;
  file?: Prisma.FileOrderByWithRelationInput;
};

export type FileShareWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    token?: string;
    AND?: Prisma.FileShareWhereInput | Prisma.FileShareWhereInput[];
    OR?: Prisma.FileShareWhereInput[];
    NOT?: Prisma.FileShareWhereInput | Prisma.FileShareWhereInput[];
    createdAt?: Prisma.DateTimeFilter<'FileShare'> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<'FileShare'> | Date | string;
    fileId?: Prisma.StringFilter<'FileShare'> | string;
    expiresAt?: Prisma.DateTimeNullableFilter<'FileShare'> | Date | string | null;
    maxViews?: Prisma.IntNullableFilter<'FileShare'> | number | null;
    views?: Prisma.IntFilter<'FileShare'> | number;
    password?: Prisma.StringNullableFilter<'FileShare'> | string | null;
    file?: Prisma.XOR<Prisma.FileScalarRelationFilter, Prisma.FileWhereInput>;
  },
  'id' | 'token'
>;

export type FileShareOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  token?: Prisma.SortOrder;
  fileId?: Prisma.SortOrder;
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder;
  maxViews?: Prisma.SortOrderInput | Prisma.SortOrder;
  views?: Prisma.SortOrder;
  password?: Prisma.SortOrderInput | Prisma.SortOrder;
  _count?: Prisma.FileShareCountOrderByAggregateInput;
  _avg?: Prisma.FileShareAvgOrderByAggregateInput;
  _max?: Prisma.FileShareMaxOrderByAggregateInput;
  _min?: Prisma.FileShareMinOrderByAggregateInput;
  _sum?: Prisma.FileShareSumOrderByAggregateInput;
};

export type FileShareScalarWhereWithAggregatesInput = {
  AND?: Prisma.FileShareScalarWhereWithAggregatesInput | Prisma.FileShareScalarWhereWithAggregatesInput[];
  OR?: Prisma.FileShareScalarWhereWithAggregatesInput[];
  NOT?: Prisma.FileShareScalarWhereWithAggregatesInput | Prisma.FileShareScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<'FileShare'> | string;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'FileShare'> | Date | string;
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<'FileShare'> | Date | string;
  token?: Prisma.StringWithAggregatesFilter<'FileShare'> | string;
  fileId?: Prisma.StringWithAggregatesFilter<'FileShare'> | string;
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<'FileShare'> | Date | string | null;
  maxViews?: Prisma.IntNullableWithAggregatesFilter<'FileShare'> | number | null;
  views?: Prisma.IntWithAggregatesFilter<'FileShare'> | number;
  password?: Prisma.StringNullableWithAggregatesFilter<'FileShare'> | string | null;
};

export type FileShareCreateInput = {
  id?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  token: string;
  expiresAt?: Date | string | null;
  maxViews?: number | null;
  views?: number;
  password?: string | null;
  file: Prisma.FileCreateNestedOneWithoutSharesInput;
};

export type FileShareUncheckedCreateInput = {
  id?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  token: string;
  fileId: string;
  expiresAt?: Date | string | null;
  maxViews?: number | null;
  views?: number;
  password?: string | null;
};

export type FileShareUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  token?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  maxViews?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  views?: Prisma.IntFieldUpdateOperationsInput | number;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  file?: Prisma.FileUpdateOneRequiredWithoutSharesNestedInput;
};

export type FileShareUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  token?: Prisma.StringFieldUpdateOperationsInput | string;
  fileId?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  maxViews?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  views?: Prisma.IntFieldUpdateOperationsInput | number;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type FileShareCreateManyInput = {
  id?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  token: string;
  fileId: string;
  expiresAt?: Date | string | null;
  maxViews?: number | null;
  views?: number;
  password?: string | null;
};

export type FileShareUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  token?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  maxViews?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  views?: Prisma.IntFieldUpdateOperationsInput | number;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type FileShareUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  token?: Prisma.StringFieldUpdateOperationsInput | string;
  fileId?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  maxViews?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  views?: Prisma.IntFieldUpdateOperationsInput | number;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type FileShareListRelationFilter = {
  every?: Prisma.FileShareWhereInput;
  some?: Prisma.FileShareWhereInput;
  none?: Prisma.FileShareWhereInput;
};

export type FileShareOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type FileShareCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  token?: Prisma.SortOrder;
  fileId?: Prisma.SortOrder;
  expiresAt?: Prisma.SortOrder;
  maxViews?: Prisma.SortOrder;
  views?: Prisma.SortOrder;
  password?: Prisma.SortOrder;
};

export type FileShareAvgOrderByAggregateInput = {
  maxViews?: Prisma.SortOrder;
  views?: Prisma.SortOrder;
};

export type FileShareMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  token?: Prisma.SortOrder;
  fileId?: Prisma.SortOrder;
  expiresAt?: Prisma.SortOrder;
  maxViews?: Prisma.SortOrder;
  views?: Prisma.SortOrder;
  password?: Prisma.SortOrder;
};

export type FileShareMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  token?: Prisma.SortOrder;
  fileId?: Prisma.SortOrder;
  expiresAt?: Prisma.SortOrder;
  maxViews?: Prisma.SortOrder;
  views?: Prisma.SortOrder;
  password?: Prisma.SortOrder;
};

export type FileShareSumOrderByAggregateInput = {
  maxViews?: Prisma.SortOrder;
  views?: Prisma.SortOrder;
};

export type FileShareCreateNestedManyWithoutFileInput = {
  create?:
    | Prisma.XOR<Prisma.FileShareCreateWithoutFileInput, Prisma.FileShareUncheckedCreateWithoutFileInput>
    | Prisma.FileShareCreateWithoutFileInput[]
    | Prisma.FileShareUncheckedCreateWithoutFileInput[];
  connectOrCreate?:
    | Prisma.FileShareCreateOrConnectWithoutFileInput
    | Prisma.FileShareCreateOrConnectWithoutFileInput[];
  createMany?: Prisma.FileShareCreateManyFileInputEnvelope;
  connect?: Prisma.FileShareWhereUniqueInput | Prisma.FileShareWhereUniqueInput[];
};

export type FileShareUncheckedCreateNestedManyWithoutFileInput = {
  create?:
    | Prisma.XOR<Prisma.FileShareCreateWithoutFileInput, Prisma.FileShareUncheckedCreateWithoutFileInput>
    | Prisma.FileShareCreateWithoutFileInput[]
    | Prisma.FileShareUncheckedCreateWithoutFileInput[];
  connectOrCreate?:
    | Prisma.FileShareCreateOrConnectWithoutFileInput
    | Prisma.FileShareCreateOrConnectWithoutFileInput[];
  createMany?: Prisma.FileShareCreateManyFileInputEnvelope;
  connect?: Prisma.FileShareWhereUniqueInput | Prisma.FileShareWhereUniqueInput[];
};

export type FileShareUpdateManyWithoutFileNestedInput = {
  create?:
    | Prisma.XOR<Prisma.FileShareCreateWithoutFileInput, Prisma.FileShareUncheckedCreateWithoutFileInput>
    | Prisma.FileShareCreateWithoutFileInput[]
    | Prisma.FileShareUncheckedCreateWithoutFileInput[];
  connectOrCreate?:
    | Prisma.FileShareCreateOrConnectWithoutFileInput
    | Prisma.FileShareCreateOrConnectWithoutFileInput[];
  upsert?:
    | Prisma.FileShareUpsertWithWhereUniqueWithoutFileInput
    | Prisma.FileShareUpsertWithWhereUniqueWithoutFileInput[];
  createMany?: Prisma.FileShareCreateManyFileInputEnvelope;
  set?: Prisma.FileShareWhereUniqueInput | Prisma.FileShareWhereUniqueInput[];
  disconnect?: Prisma.FileShareWhereUniqueInput | Prisma.FileShareWhereUniqueInput[];
  delete?: Prisma.FileShareWhereUniqueInput | Prisma.FileShareWhereUniqueInput[];
  connect?: Prisma.FileShareWhereUniqueInput | Prisma.FileShareWhereUniqueInput[];
  update?:
    | Prisma.FileShareUpdateWithWhereUniqueWithoutFileInput
    | Prisma.FileShareUpdateWithWhereUniqueWithoutFileInput[];
  updateMany?:
    | Prisma.FileShareUpdateManyWithWhereWithoutFileInput
    | Prisma.FileShareUpdateManyWithWhereWithoutFileInput[];
  deleteMany?: Prisma.FileShareScalarWhereInput | Prisma.FileShareScalarWhereInput[];
};

export type FileShareUncheckedUpdateManyWithoutFileNestedInput = {
  create?:
    | Prisma.XOR<Prisma.FileShareCreateWithoutFileInput, Prisma.FileShareUncheckedCreateWithoutFileInput>
    | Prisma.FileShareCreateWithoutFileInput[]
    | Prisma.FileShareUncheckedCreateWithoutFileInput[];
  connectOrCreate?:
    | Prisma.FileShareCreateOrConnectWithoutFileInput
    | Prisma.FileShareCreateOrConnectWithoutFileInput[];
  upsert?:
    | Prisma.FileShareUpsertWithWhereUniqueWithoutFileInput
    | Prisma.FileShareUpsertWithWhereUniqueWithoutFileInput[];
  createMany?: Prisma.FileShareCreateManyFileInputEnvelope;
  set?: Prisma.FileShareWhereUniqueInput | Prisma.FileShareWhereUniqueInput[];
  disconnect?: Prisma.FileShareWhereUniqueInput | Prisma.FileShareWhereUniqueInput[];
  delete?: Prisma.FileShareWhereUniqueInput | Prisma.FileShareWhereUniqueInput[];
  connect?: Prisma.FileShareWhereUniqueInput | Prisma.FileShareWhereUniqueInput[];
  update?:
    | Prisma.FileShareUpdateWithWhereUniqueWithoutFileInput
    | Prisma.FileShareUpdateWithWhereUniqueWithoutFileInput[];
  updateMany?:
    | Prisma.FileShareUpdateManyWithWhereWithoutFileInput
    | Prisma.FileShareUpdateManyWithWhereWithoutFileInput[];
  deleteMany?: Prisma.FileShareScalarWhereInput | Prisma.FileShareScalarWhereInput[];
};

export type FileShareCreateWithoutFileInput = {
  id?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  token: string;
  expiresAt?: Date | string | null;
  maxViews?: number | null;
  views?: number;
  password?: string | null;
};

export type FileShareUncheckedCreateWithoutFileInput = {
  id?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  token: string;
  expiresAt?: Date | string | null;
  maxViews?: number | null;
  views?: number;
  password?: string | null;
};

export type FileShareCreateOrConnectWithoutFileInput = {
  where: Prisma.FileShareWhereUniqueInput;
  create: Prisma.XOR<Prisma.FileShareCreateWithoutFileInput, Prisma.FileShareUncheckedCreateWithoutFileInput>;
};

export type FileShareCreateManyFileInputEnvelope = {
  data: Prisma.FileShareCreateManyFileInput | Prisma.FileShareCreateManyFileInput[];
  skipDuplicates?: boolean;
};

export type FileShareUpsertWithWhereUniqueWithoutFileInput = {
  where: Prisma.FileShareWhereUniqueInput;
  update: Prisma.XOR<Prisma.FileShareUpdateWithoutFileInput, Prisma.FileShareUncheckedUpdateWithoutFileInput>;
  create: Prisma.XOR<Prisma.FileShareCreateWithoutFileInput, Prisma.FileShareUncheckedCreateWithoutFileInput>;
};

export type FileShareUpdateWithWhereUniqueWithoutFileInput = {
  where: Prisma.FileShareWhereUniqueInput;
  data: Prisma.XOR<Prisma.FileShareUpdateWithoutFileInput, Prisma.FileShareUncheckedUpdateWithoutFileInput>;
};

export type FileShareUpdateManyWithWhereWithoutFileInput = {
  where: Prisma.FileShareScalarWhereInput;
  data: Prisma.XOR<
    Prisma.FileShareUpdateManyMutationInput,
    Prisma.FileShareUncheckedUpdateManyWithoutFileInput
  >;
};

export type FileShareScalarWhereInput = {
  AND?: Prisma.FileShareScalarWhereInput | Prisma.FileShareScalarWhereInput[];
  OR?: Prisma.FileShareScalarWhereInput[];
  NOT?: Prisma.FileShareScalarWhereInput | Prisma.FileShareScalarWhereInput[];
  id?: Prisma.StringFilter<'FileShare'> | string;
  createdAt?: Prisma.DateTimeFilter<'FileShare'> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<'FileShare'> | Date | string;
  token?: Prisma.StringFilter<'FileShare'> | string;
  fileId?: Prisma.StringFilter<'FileShare'> | string;
  expiresAt?: Prisma.DateTimeNullableFilter<'FileShare'> | Date | string | null;
  maxViews?: Prisma.IntNullableFilter<'FileShare'> | number | null;
  views?: Prisma.IntFilter<'FileShare'> | number;
  password?: Prisma.StringNullableFilter<'FileShare'> | string | null;
};

export type FileShareCreateManyFileInput = {
  id?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  token: string;
  expiresAt?: Date | string | null;
  maxViews?: number | null;
  views?: number;
  password?: string | null;
};

export type FileShareUpdateWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  token?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  maxViews?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  views?: Prisma.IntFieldUpdateOperationsInput | number;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type FileShareUncheckedUpdateWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  token?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  maxViews?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  views?: Prisma.IntFieldUpdateOperationsInput | number;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type FileShareUncheckedUpdateManyWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  token?: Prisma.StringFieldUpdateOperationsInput | string;
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  maxViews?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  views?: Prisma.IntFieldUpdateOperationsInput | number;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type FileShareSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    token?: boolean;
    fileId?: boolean;
    expiresAt?: boolean;
    maxViews?: boolean;
    views?: boolean;
    password?: boolean;
    file?: boolean | Prisma.FileDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['fileShare']
>;

export type FileShareSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    token?: boolean;
    fileId?: boolean;
    expiresAt?: boolean;
    maxViews?: boolean;
    views?: boolean;
    password?: boolean;
    file?: boolean | Prisma.FileDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['fileShare']
>;

export type FileShareSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    token?: boolean;
    fileId?: boolean;
    expiresAt?: boolean;
    maxViews?: boolean;
    views?: boolean;
    password?: boolean;
    file?: boolean | Prisma.FileDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['fileShare']
>;

export type FileShareSelectScalar = {
  id?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
  token?: boolean;
  fileId?: boolean;
  expiresAt?: boolean;
  maxViews?: boolean;
  views?: boolean;
  password?: boolean;
};

export type FileShareOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'createdAt' | 'updatedAt' | 'token' | 'fileId' | 'expiresAt' | 'maxViews' | 'views' | 'password',
  ExtArgs['result']['fileShare']
>;
export type FileShareInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  file?: boolean | Prisma.FileDefaultArgs<ExtArgs>;
};
export type FileShareIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  file?: boolean | Prisma.FileDefaultArgs<ExtArgs>;
};
export type FileShareIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  file?: boolean | Prisma.FileDefaultArgs<ExtArgs>;
};

export type $FileSharePayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'FileShare';
  objects: {
    file: Prisma.$FilePayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      createdAt: Date;
      updatedAt: Date;
      token: string;
      fileId: string;
      expiresAt: Date | null;
      maxViews: number | null;
      views: number;
      password: string | null;
    },
    ExtArgs['result']['fileShare']
  >;
  composites: {};
};

export type FileShareGetPayload<S extends boolean | null | undefined | FileShareDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$FileSharePayload, S>;

export type FileShareCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<FileShareFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: FileShareCountAggregateInputType | true;
};

export interface FileShareDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FileShare']; meta: { name: 'FileShare' } };
  /**
   * Find zero or one FileShare that matches the filter.
   * @param {FileShareFindUniqueArgs} args - Arguments to find a FileShare
   * @example
   * // Get one FileShare
   * const fileShare = await prisma.fileShare.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FileShareFindUniqueArgs>(
    args: Prisma.SelectSubset<T, FileShareFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__FileShareClient<
    runtime.Types.Result.GetResult<
      Prisma.$FileSharePayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one FileShare that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FileShareFindUniqueOrThrowArgs} args - Arguments to find a FileShare
   * @example
   * // Get one FileShare
   * const fileShare = await prisma.fileShare.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FileShareFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, FileShareFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__FileShareClient<
    runtime.Types.Result.GetResult<
      Prisma.$FileSharePayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first FileShare that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileShareFindFirstArgs} args - Arguments to find a FileShare
   * @example
   * // Get one FileShare
   * const fileShare = await prisma.fileShare.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FileShareFindFirstArgs>(
    args?: Prisma.SelectSubset<T, FileShareFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__FileShareClient<
    runtime.Types.Result.GetResult<
      Prisma.$FileSharePayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first FileShare that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileShareFindFirstOrThrowArgs} args - Arguments to find a FileShare
   * @example
   * // Get one FileShare
   * const fileShare = await prisma.fileShare.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FileShareFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, FileShareFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__FileShareClient<
    runtime.Types.Result.GetResult<
      Prisma.$FileSharePayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more FileShares that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileShareFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FileShares
   * const fileShares = await prisma.fileShare.findMany()
   *
   * // Get first 10 FileShares
   * const fileShares = await prisma.fileShare.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const fileShareWithIdOnly = await prisma.fileShare.findMany({ select: { id: true } })
   *
   */
  findMany<T extends FileShareFindManyArgs>(
    args?: Prisma.SelectSubset<T, FileShareFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$FileSharePayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>
  >;

  /**
   * Create a FileShare.
   * @param {FileShareCreateArgs} args - Arguments to create a FileShare.
   * @example
   * // Create one FileShare
   * const FileShare = await prisma.fileShare.create({
   *   data: {
   *     // ... data to create a FileShare
   *   }
   * })
   *
   */
  create<T extends FileShareCreateArgs>(
    args: Prisma.SelectSubset<T, FileShareCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__FileShareClient<
    runtime.Types.Result.GetResult<Prisma.$FileSharePayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many FileShares.
   * @param {FileShareCreateManyArgs} args - Arguments to create many FileShares.
   * @example
   * // Create many FileShares
   * const fileShare = await prisma.fileShare.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends FileShareCreateManyArgs>(
    args?: Prisma.SelectSubset<T, FileShareCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many FileShares and returns the data saved in the database.
   * @param {FileShareCreateManyAndReturnArgs} args - Arguments to create many FileShares.
   * @example
   * // Create many FileShares
   * const fileShare = await prisma.fileShare.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many FileShares and only return the `id`
   * const fileShareWithIdOnly = await prisma.fileShare.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends FileShareCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, FileShareCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$FileSharePayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a FileShare.
   * @param {FileShareDeleteArgs} args - Arguments to delete one FileShare.
   * @example
   * // Delete one FileShare
   * const FileShare = await prisma.fileShare.delete({
   *   where: {
   *     // ... filter to delete one FileShare
   *   }
   * })
   *
   */
  delete<T extends FileShareDeleteArgs>(
    args: Prisma.SelectSubset<T, FileShareDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__FileShareClient<
    runtime.Types.Result.GetResult<Prisma.$FileSharePayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one FileShare.
   * @param {FileShareUpdateArgs} args - Arguments to update one FileShare.
   * @example
   * // Update one FileShare
   * const fileShare = await prisma.fileShare.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends FileShareUpdateArgs>(
    args: Prisma.SelectSubset<T, FileShareUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__FileShareClient<
    runtime.Types.Result.GetResult<Prisma.$FileSharePayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more FileShares.
   * @param {FileShareDeleteManyArgs} args - Arguments to filter FileShares to delete.
   * @example
   * // Delete a few FileShares
   * const { count } = await prisma.fileShare.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends FileShareDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, FileShareDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more FileShares.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileShareUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FileShares
   * const fileShare = await prisma.fileShare.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends FileShareUpdateManyArgs>(
    args: Prisma.SelectSubset<T, FileShareUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more FileShares and returns the data updated in the database.
   * @param {FileShareUpdateManyAndReturnArgs} args - Arguments to update many FileShares.
   * @example
   * // Update many FileShares
   * const fileShare = await prisma.fileShare.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more FileShares and only return the `id`
   * const fileShareWithIdOnly = await prisma.fileShare.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends FileShareUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, FileShareUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$FileSharePayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one FileShare.
   * @param {FileShareUpsertArgs} args - Arguments to update or create a FileShare.
   * @example
   * // Update or create a FileShare
   * const fileShare = await prisma.fileShare.upsert({
   *   create: {
   *     // ... data to create a FileShare
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FileShare we want to update
   *   }
   * })
   */
  upsert<T extends FileShareUpsertArgs>(
    args: Prisma.SelectSubset<T, FileShareUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__FileShareClient<
    runtime.Types.Result.GetResult<Prisma.$FileSharePayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of FileShares.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileShareCountArgs} args - Arguments to filter FileShares to count.
   * @example
   * // Count the number of FileShares
   * const count = await prisma.fileShare.count({
   *   where: {
   *     // ... the filter for the FileShares we want to count
   *   }
   * })
   **/
  count<T extends FileShareCountArgs>(
    args?: Prisma.Subset<T, FileShareCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FileShareCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a FileShare.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileShareAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends FileShareAggregateArgs>(
    args: Prisma.Subset<T, FileShareAggregateArgs>,
  ): Prisma.PrismaPromise<GetFileShareAggregateType<T>>;

  /**
   * Group by FileShare.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileShareGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends FileShareGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends (Prisma.True extends HasSelectOrTake
      ? { orderBy: FileShareGroupByArgs['orderBy'] }
      : { orderBy?: FileShareGroupByArgs['orderBy'] }),
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends (T['by'] extends never[] ? Prisma.True : Prisma.False),
    InputErrors extends (ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]),
  >(
    args: Prisma.SubsetIntersection<T, FileShareGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors ? GetFileShareGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the FileShare model
   */
  readonly fields: FileShareFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FileShare.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FileShareClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  file<T extends Prisma.FileDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.FileDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__FileClient<
    | runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the FileShare model
 */
export interface FileShareFieldRefs {
  readonly id: Prisma.FieldRef<'FileShare', 'String'>;
  readonly createdAt: Prisma.FieldRef<'FileShare', 'DateTime'>;
  readonly updatedAt: Prisma.FieldRef<'FileShare', 'DateTime'>;
  readonly token: Prisma.FieldRef<'FileShare', 'String'>;
  readonly fileId: Prisma.FieldRef<'FileShare', 'String'>;
  readonly expiresAt: Prisma.FieldRef<'FileShare', 'DateTime'>;
  readonly maxViews: Prisma.FieldRef<'FileShare', 'Int'>;
  readonly views: Prisma.FieldRef<'FileShare', 'Int'>;
  readonly password: Prisma.FieldRef<'FileShare', 'String'>;
}

// Custom InputTypes
/**
 * FileShare findUnique
 */
export type FileShareFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareInclude<ExtArgs> | null;
  /**
   * Filter, which FileShare to fetch.
   */
  where: Prisma.FileShareWhereUniqueInput;
};

/**
 * FileShare findUniqueOrThrow
 */
export type FileShareFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareInclude<ExtArgs> | null;
  /**
   * Filter, which FileShare to fetch.
   */
  where: Prisma.FileShareWhereUniqueInput;
};

/**
 * FileShare findFirst
 */
export type FileShareFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareInclude<ExtArgs> | null;
  /**
   * Filter, which FileShare to fetch.
   */
  where?: Prisma.FileShareWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of FileShares to fetch.
   */
  orderBy?: Prisma.FileShareOrderByWithRelationInput | Prisma.FileShareOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for FileShares.
   */
  cursor?: Prisma.FileShareWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` FileShares from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` FileShares.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of FileShares.
   */
  distinct?: Prisma.FileShareScalarFieldEnum | Prisma.FileShareScalarFieldEnum[];
};

/**
 * FileShare findFirstOrThrow
 */
export type FileShareFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareInclude<ExtArgs> | null;
  /**
   * Filter, which FileShare to fetch.
   */
  where?: Prisma.FileShareWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of FileShares to fetch.
   */
  orderBy?: Prisma.FileShareOrderByWithRelationInput | Prisma.FileShareOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for FileShares.
   */
  cursor?: Prisma.FileShareWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` FileShares from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` FileShares.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of FileShares.
   */
  distinct?: Prisma.FileShareScalarFieldEnum | Prisma.FileShareScalarFieldEnum[];
};

/**
 * FileShare findMany
 */
export type FileShareFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareInclude<ExtArgs> | null;
  /**
   * Filter, which FileShares to fetch.
   */
  where?: Prisma.FileShareWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of FileShares to fetch.
   */
  orderBy?: Prisma.FileShareOrderByWithRelationInput | Prisma.FileShareOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing FileShares.
   */
  cursor?: Prisma.FileShareWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` FileShares from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` FileShares.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of FileShares.
   */
  distinct?: Prisma.FileShareScalarFieldEnum | Prisma.FileShareScalarFieldEnum[];
};

/**
 * FileShare create
 */
export type FileShareCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareInclude<ExtArgs> | null;
  /**
   * The data needed to create a FileShare.
   */
  data: Prisma.XOR<Prisma.FileShareCreateInput, Prisma.FileShareUncheckedCreateInput>;
};

/**
 * FileShare createMany
 */
export type FileShareCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many FileShares.
   */
  data: Prisma.FileShareCreateManyInput | Prisma.FileShareCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * FileShare createManyAndReturn
 */
export type FileShareCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * The data used to create many FileShares.
   */
  data: Prisma.FileShareCreateManyInput | Prisma.FileShareCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * FileShare update
 */
export type FileShareUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareInclude<ExtArgs> | null;
  /**
   * The data needed to update a FileShare.
   */
  data: Prisma.XOR<Prisma.FileShareUpdateInput, Prisma.FileShareUncheckedUpdateInput>;
  /**
   * Choose, which FileShare to update.
   */
  where: Prisma.FileShareWhereUniqueInput;
};

/**
 * FileShare updateMany
 */
export type FileShareUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update FileShares.
   */
  data: Prisma.XOR<Prisma.FileShareUpdateManyMutationInput, Prisma.FileShareUncheckedUpdateManyInput>;
  /**
   * Filter which FileShares to update
   */
  where?: Prisma.FileShareWhereInput;
  /**
   * Limit how many FileShares to update.
   */
  limit?: number;
};

/**
 * FileShare updateManyAndReturn
 */
export type FileShareUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * The data used to update FileShares.
   */
  data: Prisma.XOR<Prisma.FileShareUpdateManyMutationInput, Prisma.FileShareUncheckedUpdateManyInput>;
  /**
   * Filter which FileShares to update
   */
  where?: Prisma.FileShareWhereInput;
  /**
   * Limit how many FileShares to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * FileShare upsert
 */
export type FileShareUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareInclude<ExtArgs> | null;
  /**
   * The filter to search for the FileShare to update in case it exists.
   */
  where: Prisma.FileShareWhereUniqueInput;
  /**
   * In case the FileShare found by the `where` argument doesn't exist, create a new FileShare with this data.
   */
  create: Prisma.XOR<Prisma.FileShareCreateInput, Prisma.FileShareUncheckedCreateInput>;
  /**
   * In case the FileShare was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FileShareUpdateInput, Prisma.FileShareUncheckedUpdateInput>;
};

/**
 * FileShare delete
 */
export type FileShareDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareInclude<ExtArgs> | null;
  /**
   * Filter which FileShare to delete.
   */
  where: Prisma.FileShareWhereUniqueInput;
};

/**
 * FileShare deleteMany
 */
export type FileShareDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which FileShares to delete
   */
  where?: Prisma.FileShareWhereInput;
  /**
   * Limit how many FileShares to delete.
   */
  limit?: number;
};

/**
 * FileShare without action
 */
export type FileShareDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileShare
   */
  select?: Prisma.FileShareSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileShare
   */
  omit?: Prisma.FileShareOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileShareInclude<ExtArgs> | null;
};
